# Generated by Django 3.0.3 on 2021-03-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинг', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
