# Generated by Django 3.0.3 on 2021-03-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210309_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='description_uk',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name_uk',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_uk',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_uk',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='description_uk',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name_uk',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='country_uk',
            new_name='country_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description_uk',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tagline_uk',
            new_name='tagline_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title_uk',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='movieshot',
            old_name='description_uk',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='movieshot',
            old_name='title_uk',
            new_name='title_en',
        ),
    ]
